packages:
  - "compiler"
  - "crates/raven-node"
  - "packages/*"
  - "framework/*"
  - "vscode/extension"
  - "vscode/language-server"
  - "examples/*"
  - "website/raven-site"
onlyBuiltDependencies:
  - esbuild
  - "@vscode/vsce-sign"
