/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Runs the optimizer over a serialized AST and returns the optimized AST,
 * still serialized. Mirrors `optimize()` in `compiler/src/optimizer/index.ts`.
 *
 * Note the one intentional behavior difference from the pre-port TS
 * implementation, documented in `raven_core::optimizer`'s module doc
 * comment: `ModelDeclaration`/`ImportDeclaration` statements are preserved
 * instead of being silently dropped (a real bug in the TS switch, which has
 * no case and no default for those two variants).
 *
 * # Example
 * ```js
 * const { optimizeProgram } = require("raven-node");
 * const optimizedJson = optimizeProgram(JSON.stringify(ast));
 * const optimized = JSON.parse(optimizedJson);
 * ```
 */
export declare function optimizeProgram(astJson: string): string
/**
 * Emits JS (and optionally a v3 source map) from a serialized AST. Mirrors
 * `Emitter#emit` / `Emitter#emitWithSourceMap` in `emitter/emitter.ts`.
 *
 * `options_json`, when present, deserializes to
 * `{ sourceMap?: boolean, sourceFile?: string, sourceContent?: string }`.
 * Returns `JSON.stringify({ code, map })` — `map` is `null` unless
 * `sourceMap: true` was passed.
 *
 * # Example
 * ```js
 * const { emitProgram } = require("raven-node");
 * const resultJson = emitProgram(JSON.stringify(ast), JSON.stringify({
 *   sourceMap: true,
 *   sourceFile: "main.rv",
 * }));
 * const { code, map } = JSON.parse(resultJson);
 * ```
 */
export declare function emitProgram(astJson: string, optionsJson?: string | undefined | null): string
/**
 * Full pipeline in one native call: lex + parse + check + optimize + emit.
 * This is the Phase 3 goal call — it lets `compileFile` stop parsing the
 * source twice (once in TS for `optimize`/`Emitter`, once in Rust for
 * diagnostics — see the comment on `compileFile` in `cli/pipeline.ts`).
 *
 * `options_json` mirrors `emit_program`'s options. `registry` is the same
 * shared `Registry` object `check_source`/`bindings_for` already take —
 * cross-file `model` resolution goes through it exactly the same way.
 *
 * Returns `JSON.stringify({ diagnostics, code, map })`. `code`/`map` are
 * `null` when there's at least one error-severity diagnostic, mirroring
 * `compileFile`'s existing short-circuit (`diagnostics.some(d => d.severity
 * === "error")`).
 *
 * # Example
 * ```js
 * const { compileSource, Registry } = require("raven-node");
 * const registry = new Registry();
 * const resultJson = compileSource(source, "main.rv", JSON.stringify({
 *   sourceMap: true,
 *   sourceFile: "main.rv",
 * }), registry);
 * const { diagnostics, code, map } = JSON.parse(resultJson);
 * ```
 */
export declare function compileSource(source: string, file: string, optionsJson?: string | undefined | null, registry?: Registry | undefined | null): string
/**
 * Check source text directly (Phase 2 boundary: source in, diagnostics out).
 *
 * This is the new FFI contract — no JSON AST crosses the boundary. The
 * TypeScript `tokenize` + `Parser` step is now inside `raven-core`.
 *
 * Returns `{"diagnostics": [...]}`. Bindings/types are intentionally not
 * included — the CLI path never needs them. Call `bindings_for` when hover/
 * go-to-def data is required.
 *
 * # Example
 *
 * ```js
 * const { checkSource, Registry } = require("raven-node");
 * const registry = new Registry();
 * const result = JSON.parse(checkSource(
 *   'let x = "hi"',
 *   "hello.rv",
 *   JSON.stringify({ file: "hello.rv" }),
 *   registry,
 * ));
 * result.diagnostics; // []
 * ```
 */
export declare function checkSource(source: string, file: string, options?: string | undefined | null, registry?: Registry | undefined | null): string
/**
 * Lazily fetch bindings and exported types for a file.
 *
 * The CLI `compileFile` path never needs per-symbol bindings — only the
 * language server's hover/go-to-def does. Calling this separately avoids
 * building the 53–63 KB `bindings` JSON on every `check_source` call, which
 * was ~50% of the Phase 1 medium-file cost (`phase1-ffi-analysis.md:22`).
 *
 * Returns `{"bindings": [...], "types": {...}, "diagnostics": [...]}`.
 * Diagnostics are included so the caller does not need to call both
 * `check_source` and `bindings_for` to get hover data on a file with errors.
 *
 * # Example
 *
 * ```js
 * const { bindingsFor, Registry } = require("raven-node");
 * const registry = new Registry();
 * const result = JSON.parse(bindingsFor(
 *   'let x = 1',
 *   "x.rv",
 *   JSON.stringify({ file: "x.rv" }),
 *   registry,
 * ));
 * result.bindings; // [{ name: "x", ... }]
 * ```
 */
export declare function bindingsFor(source: string, file: string, options?: string | undefined | null, registry?: Registry | undefined | null): string
/**
 * Deprecated Phase 1 entry: JSON AST in → diagnostics+bindings+types out.
 *
 * Kept only for the differential harness that tests checker-in-isolation
 * (AST-in). New code must use `check_source` / `bindings_for`. This will be
 * deleted once the TS side no longer calls it — no two live paths past this
 * PR (AGENTS.md phase discipline).
 */
export declare function checkProgram(ast: string, options?: string | undefined | null, registry?: Registry | undefined | null): string
/** A shared, mutable workspace registry. */
export declare class Registry {
  constructor()
  /**
   * Publish a model under `name`, mirroring `WorkspaceRegistry.publish`.
   *
   * # Example
   *
   * ```js
   * const { Registry } = require("raven-node");
   * const registry = new Registry();
   * const result = JSON.parse(registry.publish(
   *   "User", JSON.stringify({ kind: "record", fields: { id: "number" } }),
   *   false, "models.rv", JSON.stringify({ file: "models.rv", start: 0, end: 4 })
   * ));
   * result.ok; // true
   * ```
   */
  publish(name: string, typeJson: string, external: boolean, file: string, locationJson: string): string
  /** Look up a published model by name. */
  lookup(name: string): string | null
  /** Every published model. */
  all(): Array<string>
  /** Every published model name. */
  names(): Array<string>
}
