/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Typecheck a single program given its JSON AST. Mirrors the TS
 * `TypeChecker.check` + `getBinder` + `getExportedFunctions` combo and the
 * `checkSource` contract in `cli/pipeline.ts`.
 *
 * Returns a JSON object:
 *
 * ```json
 * {
 *   "diagnostics": [{ "code": "RAV1001", "severity": "error", ... }],
 *   "bindings": [{ "name": "x", "kind": "variable", "type": "number", ... }],
 *   "types": { "foo": { "params": ["string"], "returnType": "number" } }
 * }
 * ```
 *
 * When a [`Registry`] instance is supplied, the same registry is shared
 * across calls (taken out for the duration of the check and put back
 * afterwards), matching how `project.ts` maintains one registry across files.
 *
 * # Example
 *
 * ```js
 * const { checkProgram, Registry } = require("raven-node");
 * const registry = new Registry();
 * const result = JSON.parse(checkProgram(
 *   JSON.stringify({ type: "Program", body: [] }),
 *   JSON.stringify({ file: "empty.rv" }),
 *   registry,
 * ));
 * result.diagnostics; // []
 * ```
 */
export declare function checkProgram(ast: string, options?: string | undefined | null, registry?: Registry | undefined | null): string
/**
 * A shared, mutable workspace registry, mirroring the TS `WorkspaceRegistry`.
 *
 * Host bindings pass one `Registry` instance into successive
 * [`check_program`] calls so models published while checking one file are
 * visible while checking the next — exactly how `project.ts` shares a single
 * registry across every file in the project.
 */
export declare class Registry {
  constructor()
  /**
   * Publish a model under `name`, mirroring `WorkspaceRegistry.publish`.
   *
   * # Example
   *
   * ```js
   * const { Registry } = require("raven-node");
   * const registry = new Registry();
   * const result = JSON.parse(registry.publish(
   *   "User", JSON.stringify({ kind: "record", fields: { id: "number" } }),
   *   false, "models.rv", JSON.stringify({ file: "models.rv", start: 0, end: 4 })
   * ));
   * result.ok; // true
   * ```
   */
  publish(name: string, typeJson: string, external: boolean, file: string, locationJson: string): string
  /** Look up a published model by name, mirroring `WorkspaceRegistry.lookup`. */
  lookup(name: string): string | null
  /** Every published model, mirroring `WorkspaceRegistry.all`. */
  all(): Array<string>
  /** Every published model name, mirroring `WorkspaceRegistry.names`. */
  names(): Array<string>
}
